export const CHANGE_CLICKED_DAY = "CHANGE_CLICKED_DAY";
export const CHANGE_DISPLAYED_MONTH = "CHANGE_DISPLAYED_MONTH";
export const SET_TODAY_DATE = "SET_TODAY_DATE";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const OPEN_MODAL = "OPEN_MODAL";
export const APPEND_TO_LIST = "APPEND_TO_LIST";
